apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: resource-consumer  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mutant
  minReplicas: 10
  maxReplicas: 200
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50